//created on: 16.12.2016
package invoiceRules

//list any import classes here.
import edu.thi.iis.modelInvoice.Decision;
//import edu.thi.iis.invoiceModel.Invoice;
//import edu.thi.iis.invoiceModel.ResponsiblePerson;
import edu.thi.iis.ws.InvoiceModelWS;


rule "SelectPerson1"

    when
        $s : Decision(Double.valueOf(invoice.getValue()) > 10000.00)
    then
    	$s.getInvoice().setApproverWorkingPosition("TOPMANAGER");
        //$s.getRp().setValue("Top-Manager");
        //EnumXY(this = ("Top-Manager"));
        //$s.getInvoice().setValue(0);
        //update($s);

end

rule "SelectPerson2"

    when
        $s : Decision(Double.valueOf(invoice.getValue()) > 1000.00, Double.valueOf(invoice.getValue()) < 10000.00)
    then
    
    $s.getInvoice().setApproverWorkingPosition("MANAGER");
        //$s.getRp().setValue("Manager");
        //$s.getInvoice().setValue(0);
        //update($s);

end

rule "SelectPerson3"

    when
        $s : Decision(Double.valueOf(invoice.getValue()) < 1000.00)
    then
    	$s.getInvoice().setApproverWorkingPosition("EMPLOYEE");
        //$s.getRp().setValue("Mitarbeiter");
        //$s.getInvoice().setValue(0);
        //update($s);

end
